version: '3.8'

services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  fastapi:
      build:
        context: ./API  # Путь к папке с FastAPI-приложением
        dockerfile: Dockerfile
      container_name: fastapi-server
      ports:
        - "8000:8000"  # Порт FastAPI
      depends_on:
        - clickhouse  # FastAPI зависит от ClickHouse
      environment:
        - CLICKHOUSE_HOST=clickhouse  # Имя сервиса ClickHouse в Docker-сети
        - CLICKHOUSE_PORT=9000
        - CLICKHOUSE_USER=default
        - CLICKHOUSE_PASSWORD=your_secure_password  # Укажите ваш пароль
      networks:
        - app-network

networks:
  app-network:
    driver: bridge

volumes:
  clickhouse_data: